kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbarena
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbarena/veilarbarena:{{version}}
  ingresses:
    - https://veilarbarena-q1.nais.preprod.local
    - https://app-q1.adeo.no/veilarbarena
    - https://veilarbarena.dev.intern.nav.no
  port: 8080
  prometheus:
    enabled: true
    path: veilarbarena/internal/prometheus
  readiness:
    path: veilarbarena/internal/isReady
    initialDelay: 45
  liveness:
    path: veilarbarena/internal/isAlive
    initialDelay: 45
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: "1"
      memory: 1024Mi
  webproxy: true
  leaderElection: true
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
          cluster: dev-fss
        - application: poao-gcp-proxy
          namespace: pto
          cluster: dev-fss
        - application: amt-tiltak
          namespace: amt
          cluster: dev-gcp
        - application: veilarbregistrering
          namespace: paw
          cluster: dev-fss
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvveilarbarena
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /oracle/data/dev/config/veilarbarena_q1
        mountPath: /var/run/secrets/nais.io/oracle_config
      - kvPath: /oracle/data/dev/creds/veilarbarena_q1-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /kv/preprod/fss/veilarbarena/q1
        mountPath: /var/run/secrets/nais.io/vault
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  env:
    - name: MODIALOGIN_OPENAM_CLIENT_ID
      value: "modialogin-q1"
    - name: ENDRING_PAA_OPPFOELGINGSBRUKER_TOPIC
      value: aapen-fo-endringPaaOppfoelgingsBruker-v1-q1
    - name: POAO_GCP_PROXY_CLIENT_ID
      value: 1fbc8405-3eae-4f2f-9af8-7c7ba303cd52
    - name: AMT_TILTAK_CLIENT_ID
      value: 667fdef7-53e1-4b3c-bdd2-5195d72e8e98
    - name: VEILARBREGISTRERING_CLIENT_ID
      value: 687bb3b0-a83c-47b7-9562-c6f9fedcc898
    - name: TILTAKSGJENNOMFORING_API_CLIENT_ID
      value: 98a17237-0bfc-496e-ba28-cdb320960257