kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbarena
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbarena/veilarbarena:{{version}}
  ingresses:
    - https://veilarbarena.nais.adeo.no
    - https://veilarbarena.intern.nav.no
  port: 8080
  prometheus:
    enabled: true
    path: veilarbarena/internal/prometheus
  readiness:
    path: veilarbarena/internal/isReady
    initialDelay: 45
  liveness:
    path: veilarbarena/internal/isAlive
    initialDelay: 45
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: "1"
      memory: 1024Mi
  webproxy: true
  leaderElection: true
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
          cluster: prod-fss
        - application: amt-tiltak
          namespace: amt
          cluster: prod-gcp
        - application: veilarbregistrering
          namespace: paw
          cluster: prod-fss
        - application: veilarboppfolging
          namespace: pto
          cluster: prod-fss
        - application: veilarbaktivitet
          namespace: pto
          cluster: prod-fss
        - application: veilarbvedtaksstotte
          namespace: pto
          cluster: prod-fss
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: prod-gcp
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvveilarbarena
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /oracle/data/prod/config/veilarbarena
        mountPath: /var/run/secrets/nais.io/oracle_config
      - kvPath: /oracle/data/prod/creds/veilarbarena-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /kv/prod/fss/veilarbarena/default
        mountPath: /var/run/secrets/nais.io/vault
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  env:
    - name: MODIALOGIN_OPENAM_CLIENT_ID
      value: "modialogin-p"
    - name: ENDRING_PAA_OPPFOELGINGSBRUKER_TOPIC
      value: aapen-fo-endringPaaOppfoelgingsBruker-v1-p
    - name: AMT_TILTAK_CLIENT_ID
      value: 877dd682-4750-4193-8286-8ad2e08c3aab
    - name: VEILARBREGISTRERING_CLIENT_ID
      value: b898d7c6-0160-4dca-867e-873a4bd85d25
    - name: TILTAKSGJENNOMFORING_API_CLIENT_ID
      value: 4bc6277f-7c25-49b9-803f-a9873995889f
