kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbarena
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbarena/veilarbarena:{{version}}
  ingresses:
    - https://veilarbarena-q1.nais.preprod.local
    - https://app-q1.adeo.no/veilarbarena
  port: 8080
  prometheus:
    enabled: true
    path: veilarbarena/internal/prometheus
  readiness:
    path: veilarbarena/internal/isReady
    initialDelay: 45
  liveness:
    path: veilarbarena/internal/isAlive
    initialDelay: 45
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: "1"
      memory: 1024Mi
  webproxy: true
  leaderElection: true
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvveilarbarena
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /oracle/data/dev/creds/veilarbarena_q1-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /kv/preprod/fss/veilarbarena/q1
        mountPath: /var/run/secrets/nais.io/vault
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
    - secret: veilarbarena-db-url
  env:
    - name: MODIALOGIN_OPENAM_CLIENT_ID
      value: "modialogin-q1"