kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbarena
  namespace: pto
  labels:
    team: pto
spec:
  image: {{image}}
  ingresses:
    - https://veilarbarena.dev-fss-pub.nais.io
    - https://veilarbarena-q1.nais.preprod.local
    - https://app-q1.adeo.no/veilarbarena
    - https://veilarbarena.dev.intern.nav.no
    - https://veilarbarena.intern.dev.nav.no
  port: 8080
  prometheus:
    enabled: true
    path: veilarbarena/internal/prometheus
  readiness:
    path: veilarbarena/internal/isReady
    initialDelay: 45
  liveness:
    path: veilarbarena/internal/isAlive
    initialDelay: 45
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: "1"
      memory: 1024Mi
  webproxy: true
  leaderElection: true
  kafka:
    pool: nav-dev
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
          cluster: dev-fss
        - application: veilarbregistrering
          namespace: paw
          cluster: dev-fss
        - application: veilarbregistrering
          namespace: paw
          cluster: dev-gcp
        - application: veilarboppfolging
          namespace: pto
          cluster: dev-fss
        - application: veilarbaktivitet
          namespace: pto
          cluster: dev-fss
        - application: veilarbvedtaksstotte
          namespace: pto
          cluster: dev-fss
        - application: poao-tilgang
          namespace: poao
          cluster: dev-gcp
        - application: poao-tilgang
          namespace: poao
          cluster: dev-fss
        - application: amt-person-service
          namespace: amt
          cluster: dev-gcp
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
        - application: veilarbportefolje
          namespace: pto
          cluster: dev-fss
        - application: veilarbportefolje
          namespace: obo
          cluster: dev-gcp
        - application: veilarbaktivitet
          namespace: dab
          cluster: dev-gcp
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvveilarbarena
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /oracle/data/dev/config/veilarbarena_q1 # Feil i navn, vi bruker (nesten) q2 nå
        mountPath: /var/run/secrets/nais.io/oracle_config
      - kvPath: /oracle/data/dev/creds/veilarbarena_q1-user # Feil i navn, vi bruker (nesten) q2 nå
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /kv/preprod/fss/veilarbarena/q1 # Feil i navn, vi bruker (nesten) q2 nå
        mountPath: /var/run/secrets/nais.io/vault
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  env:
    - name: ENDRING_PAA_OPPFOELGINGSBRUKER_TOPIC
      value: pto.endring-paa-oppfolgingsbruker-v2
    - name: AMT_TILTAK_CLIENT_ID
      value: dd1086a6-9b1d-4d7e-914e-3d868fb068a7
    - name: VEILARBREGISTRERING_CLIENT_ID
      value: be687d07-407c-43d5-941c-c2dd9939fc00
    - name: VEILARBREGISTRERING_CLIENT_ID_GCP
      value: 8da37db8-6021-4e08-81b3-99045e2c1704
    - name: TILTAKSGJENNOMFORING_API_CLIENT_ID
      value: 98a17237-0bfc-496e-ba28-cdb320960257
    - name: POAO_TILGANG_GCP_CLIENT_ID
      value: 986c77da-3cfa-4a9e-b11d-b3d193ada8cd
    - name: POAO_TILGANG_FSS_CLIENT_ID
      value: f49ec26a-1bac-4fe4-b234-39a3902acd12
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao.svc.nais.local
    - name: POAO_TILGANG_SCOPE
      value: api://dev-fss.poao.poao-tilgang/.default
    - name: AMT_PERSON_SERVICE_CLIENT_ID
      value: edad39b1-51a3-40f0-a3eb-b4097e9fcca6
