kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbarena
  namespace: pto
  labels:
    team: pto
spec:
  image: {{image}}
  ingresses:
    - https://veilarbarena.prod-fss-pub.nais.io
    - https://veilarbarena.nais.adeo.no
    - https://veilarbarena.intern.nav.no
  port: 8080
  prometheus:
    enabled: true
    path: veilarbarena/internal/prometheus
  readiness:
    path: veilarbarena/internal/isReady
    initialDelay: 45
  liveness:
    path: veilarbarena/internal/isAlive
    initialDelay: 45
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: "1"
      memory: 1024Mi
  webproxy: true
  leaderElection: true
  kafka:
    pool: nav-prod
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  accessPolicy:
    outbound:
      rules:
        - application: veilarbaktivitet
          namespace: dab
          cluster: dev-gcp
    inbound:
      rules:
        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
          cluster: prod-fss
        - application: veilarbregistrering
          namespace: paw
          cluster: prod-fss
        - application: veilarbregistrering
          namespace: paw
          cluster: prod-gcp
        - application: veilarboppfolging
          namespace: pto
          cluster: prod-fss
        - application: veilarboppfolging
          namespace: poao
          cluster: prod-gcp
        - application: veilarbaktivitet
          namespace: pto
          cluster: prod-fss
        - application: veilarbvedtaksstotte
          namespace: pto
          cluster: prod-fss
        - application: veilarbvedtaksstotte
          namespace: obo
          cluster: prod-gcp
        - application: poao-tilgang
          namespace: poao
          cluster: prod-gcp
        - application: poao-tilgang
          namespace: poao
          cluster: prod-fss
        - application: amt-person-service
          namespace: amt
          cluster: prod-gcp
        - application: veilarbportefolje
          namespace: pto
          cluster: prod-fss
        - application: veilarbportefolje
          namespace: obo
          cluster: prod-gcp
        - application: veilarbaktivitet
          namespace: dab
          cluster: prod-gcp
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
        - application: oppgave
          namespace: aap
          cluster: prod-gcp
        - application: postmottak-backend
          namespace: aap
          cluster: prod-gcp
        - application: ao-oppfolgingskontor
          namespace: dab
          cluster: prod-gcp
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvveilarbarena
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /oracle/data/prod/config/veilarbarena
        mountPath: /var/run/secrets/nais.io/oracle_config
      - kvPath: /oracle/data/prod/creds/veilarbarena-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /kv/prod/fss/veilarbarena/default
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: ENDRING_PAA_OPPFOELGINGSBRUKER_TOPIC
      value: pto.endring-paa-oppfolgingsbruker-v2
    - name: AMT_TILTAK_CLIENT_ID
      value: dbd95569-e64b-4432-adcb-769015a7035b
    - name: VEILARBREGISTRERING_CLIENT_ID
      value: b898d7c6-0160-4dca-867e-873a4bd85d25
    - name: VEILARBREGISTRERING_CLIENT_ID_GCP
      value: ce413ccb-0b33-400c-a57d-7d9ffdcb496f
    - name: TILTAKSGJENNOMFORING_API_CLIENT_ID
      value: 4bc6277f-7c25-49b9-803f-a9873995889f
    - name: POAO_TILGANG_GCP_CLIENT_ID
      value: b345dcb8-d4f8-41fc-9d4e-bc169c04145b
    - name: POAO_TILGANG_FSS_CLIENT_ID
      value: f737ff0f-c86a-4a84-8d52-221410234160
    - name: AAP_OPPGAVE_CLIENT_ID
      value: 2d076bcc-3b6a-4bc7-878e-791aed30433c
    - name: AAP_POSTMOTTAK_CLIENT_ID
      value: 7f9044f1-fa3a-4356-9062-05035400fd6a
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao.svc.nais.local
    - name: POAO_TILGANG_SCOPE
      value: api://prod-fss.poao.poao-tilgang/.default
    - name: VEILARBAKTIVITET_URL
      value: https://veilarbaktivitet.intern.nav.no
    - name: VEILARBAKTIVITET_SCOPE
      value: api://prod-gcp.dab.veilarbaktivitet/.default
    - name: AMT_PERSON_SERVICE_CLIENT_ID
      value: 71948d71-65be-4335-974f-987e95fc99e5
    - name: SECURITY_TOKEN_SERVICE_DISCOVERY_URL
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: VIRKSOMHET_YTELSESKONTRAKT_V3_ENDPOINTURL
      value: https://arena.adeo.no/ail_ws/Ytelseskontrakt_v3
