
INSERT INTO OPPFOLGINGSBRUKER (PERSON_ID, FODSELSNR, ETTERNAVN, FORNAVN, FORMIDLINGSGRUPPEKODE, KVALIFISERINGSGRUPPEKODE, RETTIGHETSGRUPPEKODE, ER_DOED, TIDSSTEMPEL) VALUES (1, '12345678900', 'Nordman', 'Ola', 'ARBS', 'BFORM', 'VLONN', 'N', CURRENT_TIMESTAMP);


INSERT INTO OPPFOLGINGSBRUKER (PERSON_ID, FODSELSNR, ETTERNAVN, FORNAVN, FORMIDLINGSGRUPPEKODE, KVALIFISERINGSGRUPPEKODE, RETTIGHETSGRUPPEKODE, ER_DOED, TIDSSTEMPEL) VALUES (2, '12345678901', 'Nordman', 'Kari', 'ARBS', 'BFORM', 'VLONN', 'N', CURRENT_TIMESTAMP);


INSERT INTO OPPFOLGINGSBRUKER (PERSON_ID, FODSELSNR, ETTERNAVN, FORNAVN, FORMIDLINGSGRUPPEKODE, KVALIFISERINGSGRUPPEKODE, RETTIGHETSGRUPPEKODE, ER_DOED, TIDSSTEMPEL) VALUES (3, '12345678902', 'Nordman', 'Jens', 'IARBS', 'RANDOM_VERDI', 'VLONN', 'N', CURRENT_TIMESTAMP);


INSERT INTO OPPFOLGINGSBRUKER (PERSON_ID, FODSELSNR, ETTERNAVN, FORNAVN, FORMIDLINGSGRUPPEKODE, KVALIFISERINGSGRUPPEKODE, RETTIGHETSGRUPPEKODE, ER_DOED, TIDSSTEMPEL) VALUES (3, '12345678902', 'Nordman', 'Kåre', 'IARBS', 'BFORM', 'VLONN', 'N', CURRENT_TIMESTAMP);
