CREATE TABLE KAFKA_PRODUCER_RECORD
(
    FNR         VARCHAR(33) NOT NULL,
    TIDSSTEMPEL DATE,
    PRIMARY KEY (FNR, TIDSSTEMPEL)
);

CREATE OR REPLACE TRIGGER Arena_pa_kafka
    AFTER DELETE OR INSERT OR UPDATE
    ON OPPFOLGINGSBRUKER
BEGIN
    INSERT INTO KAFKA_PRODUCER_RECORD (FNR, TIDSSTEMPEL) VALUES (:new.FODSELSNR, :new.TIDSSTEMPEL);
END;
/